apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: yellow-book
  region: ap-southeast-1
  version: '1.31'

iam:
  withOIDC: true

managedNodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        albIngress: true
        awsLoadBalancerController: true

addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
